version: '3.7'
services:
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./srv/client/log/:/var/log/nginx/
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - 6000:6000
    volumes:
      - ./srv/server/:/app/
